export const data = [{
  address: "6649 N Blue Gum St",
  city: "New Orleans",
  company_name: "Benton, John B Jr",
  county: "Orleans",
  email: "jbutt@gmail.com",
  first_name: "James",
  id: "VA1ypxs8oY",
  last_name: "Butt",
  phone: "504-845-1427",
  state: "LA",
  userId: 1001,
  zip: 70116
}, {
  address: "4 B Blue Ridge Blvd",
  city: "Brighton",
  company_name: "Chanay, Jeffrey A Esq",
  county: "Livingston",
  email: "josephine_darakjy@darakjy.org",
  first_name: "Josephine",
  id: "wj3f2ha4ql",
  last_name: "Darakjy",
  phone: "810-374-9840",
  state: "MI",
  userId: 1001,
  zip: 48116
}, {
  address: "8 W Cerritos Ave #54",
  city: "Bridgeport",
  company_name: "Chemel, James L Cpa",
  county: "Gloucester",
  email: "art@venere.org",
  first_name: "Art",
  id: "tTCcpQKlqR",
  last_name: "Venere",
  phone: "856-264-4130",
  state: "NJ",
  userId: 1001,
  zip: 8014
}, {
  address: "639 Main St",
  city: "Anchorage",
  company_name: "Feltz Printing Service",
  county: "Anchorage",
  email: "lpaprocki@hotmail.com",
  first_name: "Lenna",
  id: "ZlTSUHyY1V",
  last_name: "Paprocki",
  phone: "907-921-2010",
  state: "AK",
  userId: 1001,
  zip: 99501
}, {
  address: "34 Center St",
  city: "Hamilton",
  company_name: "Printing Dimensions",
  county: "Butler",
  email: "donette.foller@cox.net",
  first_name: "Donette",
  id: "4ElanUA6XI",
  last_name: "Foller",
  phone: "513-549-4561",
  state: "OH",
  userId: 1001,
  zip: 45011
}, {
  address: "3 Mcauley Dr",
  city: "Ashland",
  company_name: "Chapman, Ross E Esq",
  county: "Ashland",
  email: "simona@morasca.com",
  first_name: "Simona",
  id: "KevPUGsRwn",
  last_name: "Morasca",
  phone: "419-800-6759",
  state: "OH",
  userId: 1001,
  zip: 44805
}, {
  address: "7 Eads St",
  city: "Chicago",
  company_name: "Morlong Associates",
  county: "Cook",
  email: "mitsue_tollner@yahoo.com",
  first_name: "Mitsue",
  id: "TpMoBGOhg5",
  last_name: "Tollner",
  phone: "773-924-8565",
  state: "IL",
  userId: 1001,
  zip: 60632
}, {
  address: "7 W Jackson Blvd",
  city: "San Jose",
  company_name: "Commercial Press",
  county: "Santa Clara",
  email: "leota@hotmail.com",
  first_name: "Leota",
  id: "ItubBzcGqc",
  last_name: "Dilliard",
  phone: "408-813-1105",
  state: "CA",
  userId: 1001,
  zip: 95111
}, {
  address: "5 Boston Ave #88",
  city: "Sioux Falls",
  company_name: "Truhlar And Truhlar Attys",
  county: "Minnehaha",
  email: "sage_wieser@cox.net",
  first_name: "Sage",
  id: "FuUhIT3AGq",
  last_name: "Wieser",
  phone: "605-794-4895",
  state: "SD",
  userId: 1001,
  zip: 57105
}, {
  address: "228 Runamuck Pl #2808",
  city: "Baltimore",
  company_name: "King, Christopher A Esq",
  county: "Baltimore City",
  email: "kris@gmail.com",
  first_name: "Kris",
  id: "m0PRE43gS2",
  last_name: "Marrier",
  phone: "410-804-4694",
  state: "MD",
  userId: 1001,
  zip: 21224
}, {
  address: "2371 Jerrold Ave",
  city: "Kulpsville",
  company_name: "Dorl, James J Esq",
  county: "Montgomery",
  email: "minna_amigon@yahoo.com",
  first_name: "Minna",
  id: "Ndhaoml2hF",
  last_name: "Amigon",
  phone: "215-422-8694",
  state: "PA",
  userId: 1002,
  zip: 19443
}, {
  address: "37275 St  Rt 17m M",
  city: "Middle Island",
  company_name: "Rangoni Of Florence",
  county: "Suffolk",
  email: "amaclead@gmail.com",
  first_name: "Abel",
  id: "evdpPipxcw",
  last_name: "Maclead",
  phone: "631-677-3675",
  state: "NY",
  userId: 1002,
  zip: 11953
}, {
  address: "25 E 75th St #69",
  city: "Los Angeles",
  company_name: "Feiner Bros",
  county: "Los Angeles",
  email: "kiley.caldarera@aol.com",
  first_name: "Kiley",
  id: "7MWUPRrSeB",
  last_name: "Caldarera",
  phone: "310-254-3084",
  state: "CA",
  userId: 1002,
  zip: 90034
}, {
  address: "98 Connecticut Ave Nw",
  city: "Chagrin Falls",
  company_name: "Buckley Miller &amp; Wright",
  county: "Geauga",
  email: "gruta@cox.net",
  first_name: "Graciela",
  id: "Iiwy34gyT1",
  last_name: "Ruta",
  phone: "440-579-7763",
  state: "OH",
  userId: 1002,
  zip: 44023
}, {
  address: "56 E Morehead St",
  city: "Laredo",
  company_name: "Rousseaux, Michael Esq",
  county: "Webb",
  email: "calbares@gmail.com",
  first_name: "Cammy",
  id: "kSkS9xQbp0",
  last_name: "Albares",
  phone: "956-841-7216",
  state: "TX",
  userId: 1002,
  zip: 78045
}, {
  address: "73 State Road 434 E",
  city: "Phoenix",
  company_name: "Century Communications",
  county: "Maricopa",
  email: "mattie@aol.com",
  first_name: "Mattie",
  id: "xBssWWcR40",
  last_name: "Poquette",
  phone: "602-953-6360",
  state: "AZ",
  userId: 1002,
  zip: 85013
}, {
  address: "69734 E Carrillo St",
  city: "Mc Minnville",
  company_name: "Bolton, Wilbur Esq",
  county: "Warren",
  email: "meaghan@hotmail.com",
  first_name: "Meaghan",
  id: "qKUK8Lw2LF",
  last_name: "Garufi",
  phone: "931-235-7959",
  state: "TN",
  userId: 1002,
  zip: 37110
}, {
  address: "322 New Horizon Blvd",
  city: "Milwaukee",
  company_name: "T M Byxbee Company Pc",
  county: "Milwaukee",
  email: "gladys.rim@rim.org",
  first_name: "Gladys",
  id: "A8IyvAjNgD",
  last_name: "Rim",
  phone: "414-377-2880",
  state: "WI",
  userId: 1002,
  zip: 53207
}, {
  address: "1 State Route 27",
  city: "Taylor",
  company_name: "Farmers Insurance Group",
  county: "Wayne",
  email: "yuki_whobrey@aol.com",
  first_name: "Yuki",
  id: "T3Aqod7pCb",
  last_name: "Whobrey",
  phone: "313-341-4470",
  state: "MI",
  userId: 1002,
  zip: 48180
}, {
  address: "394 Manchester Blvd",
  city: "Rockford",
  company_name: "Post Box Services Plus",
  county: "Winnebago",
  email: "fletcher.flosi@yahoo.com",
  first_name: "Fletcher",
  id: "k7Ss19cqo4",
  last_name: "Flosi",
  phone: "815-426-5657",
  state: "IL",
  userId: 1002,
  zip: 61109
}, {
  address: "6 S 33rd St",
  city: "Aston",
  company_name: "Sport En Art",
  county: "Delaware",
  email: "bette_nicka@cox.net",
  first_name: "Bette",
  id: "IQS6CB6MM9",
  last_name: "Nicka",
  phone: "610-492-4643",
  state: "PA",
  userId: 1003,
  zip: 19014
}, {
  address: "6 Greenleaf Ave",
  city: "San Jose",
  company_name: "C 4 Network Inc",
  county: "Santa Clara",
  email: "vinouye@aol.com",
  first_name: "Veronika",
  id: "Ug30UOOhZm",
  last_name: "Inouye",
  phone: "408-813-4592",
  state: "CA",
  userId: 1003,
  zip: 95111
}, {
  address: "618 W Yakima Ave",
  city: "Irving",
  company_name: "Ingalls, Donald R Esq",
  county: "Dallas",
  email: "willard@hotmail.com",
  first_name: "Willard",
  id: "3egqm8SH4q",
  last_name: "Kolmetz",
  phone: "972-896-4882",
  state: "TX",
  userId: 1003,
  zip: 75062
}, {
  address: "74 S Westgate St",
  city: "Albany",
  company_name: "Franklin, Peter L Esq",
  county: "Albany",
  email: "mroyster@royster.com",
  first_name: "Maryann",
  id: "bDhorAMSpx",
  last_name: "Royster",
  phone: "518-448-8982",
  state: "NY",
  userId: 1003,
  zip: 12204
}, {
  address: "3273 State St",
  city: "Middlesex",
  company_name: "Wtlz Power 107 Fm",
  county: "Middlesex",
  email: "alisha@slusarski.com",
  first_name: "Alisha",
  id: "U8E8diwj0G",
  last_name: "Slusarski",
  phone: "732-635-3453",
  state: "NJ",
  userId: 1003,
  zip: 8846
}, {
  address: "1 Central Ave",
  city: "Stevens Point",
  company_name: "Ledecky, David Esq",
  county: "Portage",
  email: "allene_iturbide@cox.net",
  first_name: "Allene",
  id: "l15tAYrzEg",
  last_name: "Iturbide",
  phone: "715-530-9863",
  state: "WI",
  userId: 1003,
  zip: 54481
}, {
  address: "86 Nw 66th St #8673",
  city: "Shawnee",
  company_name: "Professional Image Inc",
  county: "Johnson",
  email: "chanel.caudy@caudy.org",
  first_name: "Chanel",
  id: "Gq1UVetNy6",
  last_name: "Caudy",
  phone: "913-899-1103",
  state: "KS",
  userId: 1003,
  zip: 66218
}, {
  address: "2 Cedar Ave #84",
  city: "Easton",
  company_name: "Sider, Donald C Esq",
  county: "Talbot",
  email: "ezekiel@chui.com",
  first_name: "Ezekiel",
  id: "XBFKuH4ptm",
  last_name: "Chui",
  phone: "410-235-8738",
  state: "MD",
  userId: 1003,
  zip: 21601
}, {
  address: "90991 Thorburn Ave",
  city: "New York",
  company_name: "U Pull It",
  county: "New York",
  email: "wkusko@yahoo.com",
  first_name: "Willow",
  id: "B0oh5bpzFC",
  last_name: "Kusko",
  phone: "212-934-5167",
  state: "NY",
  userId: 1003,
  zip: 10011
}, {
  address: "386 9th Ave N",
  city: "Conroe",
  company_name: "Clark, Richard Cpa",
  county: "Montgomery",
  email: "bfigeroa@aol.com",
  first_name: "Bernardo",
  id: "PJgSjCglM2",
  last_name: "Figeroa",
  phone: "936-597-3614",
  state: "TX",
  userId: 1003,
  zip: 77301
}];

export const users = [{
  address: "74874 Atlantic Ave",
  city: "Columbus",
  company_name: "Moskowitz, Barry S",
  county: "Franklin",
  email: "ammie@corrio.com",
  first_name: "Ammie",
  id: "ZDi8RQVXiG",
  last_name: "Corrio",
  phone: "614-648-3265",
  state: "OH",
  userId: 1001,
  zip: 43215
}, {
  address: "366 South Dr",
  city: "Las Cruces",
  company_name: "Cascade Realty Advisors Inc",
  county: "Dona Ana",
  email: "francine_vocelka@vocelka.com",
  first_name: "Francine",
  id: "Dcu7Q5LUCg",
  last_name: "Vocelka",
  phone: "505-335-5293",
  state: "NM",
  userId: 1002,
  zip: 88011
}, {
  address: "45 E Liberty St",
  city: "Ridgefield Park",
  company_name: "Knwz Newsradio",
  county: "Bergen",
  email: "ernie_stenseth@aol.com",
  first_name: "Ernie",
  id: "ghQWVJnwPx",
  last_name: "Stenseth",
  phone: "201-387-9093",
  state: "NJ",
  userId: 1003,
  zip: 7660
}];

export const getUserFromId = (id) => {
  const res = users.filter(user => user.id === id);
  return res[0] || {};
}

export const dataBluePrint = {
  address: "",
  city: "",
  company_name: "",
  county: "",
  email: "",
  first_name: "",
  id: "",
  last_name: "",
  phone: "",
  state: "",
  userId: null,
  zip: ""
};
